// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3mDcy7_vEBEhKiiBdq2HjocxBJbkz_UE',
    appId: '1:842673531592:web:7cfdbdcfe609e3d7d8d3fd',
    messagingSenderId: '842673531592',
    projectId: 'noteck-flutter',
    authDomain: 'noteck-flutter.firebaseapp.com',
    storageBucket: 'noteck-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-kR9_KONru4bxrVVh-oDtkk5UssaGjPk',
    appId: '1:842673531592:android:260efeb9229128fdd8d3fd',
    messagingSenderId: '842673531592',
    projectId: 'noteck-flutter',
    storageBucket: 'noteck-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxbq5WcAWZH1qj-IeNrUAGWdu8m6umE8k',
    appId: '1:842673531592:ios:5b4a676146e2ff48d8d3fd',
    messagingSenderId: '842673531592',
    projectId: 'noteck-flutter',
    storageBucket: 'noteck-flutter.firebasestorage.app',
    iosBundleId: 'com.example.testNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxbq5WcAWZH1qj-IeNrUAGWdu8m6umE8k',
    appId: '1:842673531592:ios:5b4a676146e2ff48d8d3fd',
    messagingSenderId: '842673531592',
    projectId: 'noteck-flutter',
    storageBucket: 'noteck-flutter.firebasestorage.app',
    iosBundleId: 'com.example.testNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3mDcy7_vEBEhKiiBdq2HjocxBJbkz_UE',
    appId: '1:842673531592:web:c152bbcd04c21f00d8d3fd',
    messagingSenderId: '842673531592',
    projectId: 'noteck-flutter',
    authDomain: 'noteck-flutter.firebaseapp.com',
    storageBucket: 'noteck-flutter.firebasestorage.app',
  );
}
